version: '3'

services:
  jekaserver:
    build: ./server
    image: goodandco:jeka-server
    container_name: jeka-server
    ports:
     - 1337:1337
     - 4040:4040

  jekaclient:
    build: ./client
    image: goodandco:jeka-client
    container_name: jeka-client
    ports:
      - 8889:8888

