version: '3'

services:
  jeka-http-server-dev:
    build: ../../projects/http-server
    image: goodandco:jeka-http-server-dev
    container_name: jeka-http-server-dev
    expose:
    - 1338
    - 4041
    ports:
    - 1338:1338
    - 4041:4041
    networks:
    - asterisk
    environment:
    - NODE_ENV=production
    - HTTP_PORT=4041
    - TCP_PORT=1338
    - TCP_HOST=127.0.0.1
    - TOKEN=ololokek

  jeka-api-dev:
    build: ../../projects/api
    image: goodandco:jeka-api-dev
    container_name: jeka-api-dev
    expose:
    - 4044
    ports:
    - 4044:4044
    depends_on:
    - jeka-asteriskdb
    networks:
    - asterisk
    - mikbill
    environment:
    - NODE_ENV=production
    - ASTERISK_DB_NAME=asteriskdb
    - ASTERISK_DB_HOST=jeka-asteriskdb
    - ASTERISK_DB_USER=user123
    - ASTERISK_DB_PASSWORD=user123
    - MIKBILL_DB_NAME=mikbill
    - MIKBILL_DB_HOST=jeka-mikbilldb
    - MIKBILL_DB_USER=user123
    - MIKBILL_DB_PASSWORD=user123

  jeka-mikbilldb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3307:3306
    networks:
    - mikbill
    environment:
      MYSQL_DATABASE: mikbill
      MYSQL_USER: user123
      MYSQL_PASSWORD: user123
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - /storage/ssh/storage/docker/jeka-mikbilldb-datadir:/var/lib/mysql

  jeka-asteriskdb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306:3306
    networks:
    - asterisk
    environment:
      MYSQL_DATABASE: asteriskdb
      MYSQL_USER: user123
      MYSQL_PASSWORD: user123
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - /storage/ssh/storage/docker/jeka-asteriskdb-datadir:/var/lib/mysql

networks:
  asterisk:
    driver: bridge
  mikbill:
    driver: bridge