version: '3'

services:
  jeka-http-server-dev:
    build: ../../projects/http-server
    image: goodandco:jeka-http-server-dev
    container_name: jeka-http-server-dev
    expose:
     - 1338
     - 4041
    ports:
     - 1338:1338
     - 4041:4041
    environment:
     - NODE_ENV=production
     - HTTP_PORT=4041
     - TCP_PORT=1338
     - TCP_HOST=127.0.0.1
     - TOKEN=ololokek

  jeka-client-dev:
    build: ../../projects/client
    image: goodandco:jeka-client-dev
    container_name: jeka-client-dev
    expose:
      - 8889
    ports:
      - 8889:8889
    environment:
      - NODE_ENV=production
      - WEB_SOCKET_URL=ws://127.0.0.1:1338
      - CLIENT_PORT=8889

  jeka-mysql-db:
    image: mysql
    container_name: jeka-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: asterisk_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /storage/docker/jeka-mysql-datadir:/var/lib/mysql
