version: '3'

services:
  jeka-websocket-server:
    build: ../../projects/asterisk-server
    image: goodandco:jeka-asterisk-server
    container_name: jeka-asterisk-server
    expose:
      - 1337
    ports:
      - 1337:1337
    environment:
      - NODE_ENV=production
      - AGI_PORT=4537
      - TCP_PORT=1337
      - TCP_HOST=127.0.0.1

  jeka-api:
    build: ../../projects/api
    image: goodandco:jeka-api
    container_name: jeka-api
    expose:
      - 4044
    ports:
      - 4044:4044
    depends_on:
      - jeka-asteriskdb
    environment:
      - ASTERISK_DB_HOST=
      - ASTERISK_DB_USER=
      - ASTERISK_DB_PASSWORD=
      - MIKBILL_DB_HOST=
      - MIKBILL_DB_USER=
      - MIKBILL_DB_PASSWORD=
